project:
  type: website
  output-dir: docs

website:
  title: "Uras Uyal"
  navbar:
    left: 
      - text: "Home"
        href: index.html
      - text: "Data Viz"
        menu: 
         - text: "Space Objects"
           href: SpaceObjects.html
         - text: "Internally Displaced People (IDPs)"
           href: IDPs.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full