project:
  type: website
  output-dir: docs

website:
  title: "Uras Uyal"
  navbar:
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Data Visualization"
        menu: 
         - text: "Space Objects"
           href: SpaceObjects.html
         - text: "Campus Pride Index"
           href: SecondData.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full