project:
  type: website
  output-dir: docs

website:
  title: "My phenomenal first website!"
  navbar:
    right: 
      - text: "About Me"
        href: about.html
      - text: "Data Visualization"
        menu: 
         - text: "Mario Kart"
           href: mariokart.html
         - text: "Campus Pride Index"
           href: pride.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full