---
title: "Songs Text Analysis"
description: |
  An analysis of a dataset of songs as found on Spotify
author: Uras Uyal
date: March 5, 2025
format: html
execute: 
  warning: false
  message: false
---

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-01-21') 
tuesdata <- tidytuesdayR::tt_load(2020, week = 4)
spotify_songs <- tuesdata$spotify_songs
library(ggplot2)
```


```{r}
library(dplyr)

avg_songs_per_album <- spotify_songs |>
  group_by(playlist_genre, track_album_id) |>
  summarise(songs_per_album = n()) |>
  filter(songs_per_album > 1) |>
  group_by(playlist_genre) |>
  summarise(avg_songs_per_album = mean(songs_per_album))

print(avg_songs_per_album)
```
```{r}
songs_per_album_by_genre <- spotify_songs |>
  group_by(playlist_genre, track_album_id) |>
  summarise(songs_per_album = n()) |>
  filter(songs_per_album > 1)

ggplot(songs_per_album_by_genre, aes(x = songs_per_album, fill = playlist_genre)) +
  geom_bar(aes(y = ..count..), position = "dodge", stat = "count", show.legend = TRUE) +
  labs(x = "Number of Songs per Album", y = "Number of Albums", 
       title = "Albums by Number of Songs Included") +
  scale_fill_manual(values = c("red","green","blue","orange","purple","cyan")) + 
  scale_x_continuous(limits = c(1.5, 8), breaks = 0:8) 
```