---
title: "Objects in Space"
description: |
  An analysis of objects launched into outer space by country by year, provided by TidyTuesday
author: Uras Uyal
date: February 19, 2025
format: html
execute: 
  warning: false
  message: false
---

This mini-project analyzes trends in number of objects Russia and China have launched into space since 1957. Data is provided by the TidyTuesday library, which accessed the specific dataset from the United Nations Office for Outer Space Affairs (2024) helped by Our World in Data.

```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
tuesdata <- tidytuesdayR::tt_load('2024-04-23')
outer_space_objects <- tuesdata$outer_space_objects


outer_space_objects_filtered <- filter(outer_space_objects, Entity == "China" | Entity == "Russia")
                                       
ggplot(outer_space_objects_filtered, aes(x = Year, y = num_objects, color = Entity)) +
  geom_line(size = 1) + 
  geom_point(size = 2) +  
  labs(title = "Number of Space Objects Launched by China vs. that of Russia",
       subtitle = "A comparison of space activity since the 1950s",
       x = "Year", 
       y = "Number of Space Objects Launched",
       color = "Country",
       shape = "Country") +
  theme_gray()
```

Above is a graph of number of objects sent into space by China vs. Russia from 1957 until 2023. Between the 1960s and 2000s, Russia was quite successful in their space launches, however, through the end of this timeframe, their space launches per year started to decrease. The rise in their space launches coincided with the Cold War, and the decline coincided with the dissolution of the Soviet Union in the early 1990s. We can see that in the 1950s and 1960s, China sent no objects into space but as mass education and technology developed in China, it was gradually be able to send objects into space, taking over the lead from Russia in the mid-2010s. Russia's rise from the 1960s to the 1980s looks sort of logistical, whereas China's rise since the 1990s looks more exponential, however, it is too early to decide. The causes of these could be the major reasons behind space launches: militaristic and governmental reasons vs. more commercial oriented government backed reasons in Russia and China's cases respectively. The data set originally includes other countries and organizations around the world as well.


**Sources:**

**TidyTuesday source:** https://github.com/rfordatascience/tidytuesday/blob/main/data/2024/2024-04-23/readme.md

**Data Page:** Annual number of objects launched into space”, part of the following publication: Edouard Mathieu and Max Roser (2022) - “Space Exploration and Satellites”. Data adapted from United Nations Office for Outer Space Affairs. Retrieved from https://ourworldindata.org/grapher/yearly-number-of-objects-launched-into-outer-space

**Dataset:** United Nations Office for Outer Space Affairs (2024) – with major processing by Our World in Data. “Annual number of objects launched into space – UNOOSA” [dataset]. United Nations Office for Outer Space Affairs, “Online Index of Objects Launched into Outer Space” [original data]. Retrieved April 21, 2024 from https://ourworldindata.org/grapher/yearly-number-of-objects-launched-into-outer-space
